[package]
name = "commodityprice"
version = "0.1.0"
authors = ["Andy Nagels <thereisanewway@gmail.com>"]
edition = "2021"

[dependencies]
docopt = "=1.0.2"
chrono = "0.4"
yahoo-finance = "0.2"
pin-project-internal = "=0.4.29"