.TH COMMODITYPRICE 1 commodityprice\-VERSION
.SH NAME
commodityprice \- download historical commodity prices from yahoo finance
.SH SYNOPSIS
.B commodityprice
.RB [ \-\-help ]
.SH DEPENDS ON
The yahoo finance api.
.SH DESCRIPTION
Commodityprice is a c program, that calls the yahoo finance api to retrieve historical price information for a set of ticker symbols.
The data is printed on stdout.
.SH OPTIONS
.TP
.B \-\-version
Prints version information to standard output, then exits.
.B \-\-tickers=<json>
Json file with ticker symbol information, in the format defined by the yahoo finance api.
.B [ \-\-year=<year> ]
Used to specify the year to query. Current year is used by default.
.SH USAGE
.SH SEE ALSO
.SH BUGS
.SH EXAMPLES
commodityprice --tickers=mytickers.json --year=2023
